backend:
  name: github
  repo: linyum14/linyum14.github.io  # 예: jian/my-blog
  branch: main

# 아래 내용은 그대로 두셔도 됩니다
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "포스트(블로그 글)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일자", name: "date", widget: "datetime" }
      - { label: "설명(요약)", name: "description", widget: "string", required: false }
      - { label: "내용", name: "body", widget: "markdown" }
  - name: "wiki"
    label: "위키(설정집)"
    folder: "_wiki"
    create: true
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일자", name: "date", widget: "datetime"}
      - {label: "내용", name: "body", widget: "markdown"}