backend:
  name: git-gateway # netlify 문지기를 쓰겠다는 신호로 변경!
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "포스트(블로그 글)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일자", name: "date", widget: "datetime" }
      - { label: "설명(요약)", name: "description", widget: "string", required: false }
      - { label: "내용", name: "body", widget: "markdown" }
